### ISSUE TITLE
Setting the margin of a button causes rendering problems (Nimbus LAF)

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/swing-tree#103]
When using the `.withStyle` method with the `Nimbus` LAF and adding a margin to a button, it does not render as expected and is different from other LAF.
It is worth noting that we are currently using this behavior to construct a double button in case we change/fix this behavior. 
```Java
JPanel panel =
panel().withLayout(DEBUG).withPrefSize(150, 70)
.add(GROW, panel().withBackground(Color.ORANGE))
.add(
    button("Test")
    .withStyle(style -> style
        .marginLeft(10)
    )
)
.add(GROW, panel().withBackground(Color.ORANGE))
.get(JPanel.class);

show(panel);
```

![Screenshot from 2024-06-18 10-49-13](https://github.com/globaltcad/swing-tree/assets/44626096/48e2f133-06dd-4e4b-bd77-5a7b6d4d0e0d) 
![Screenshot from 2024-06-18 11-52-16](https://github.com/globaltcad/swing-tree/assets/44626096/c5778046-cb27-45d8-9309-4e9a51518774)

![Screenshot from 2024-06-18 10-49-40](https://github.com/globaltcad/swing-tree/assets/44626096/415e6346-e818-472a-8cbb-1dc9d030e8db)
![Screenshot from 2024-06-18 11-52-42](https://github.com/globaltcad/swing-tree/assets/44626096/2c654c31-f328-4e13-9d76-a702d0a48139)

**Comment by Gleethos** [comment]
I investigated this issue.
The problem is inside of `SynthButtonUI` which
paints the button through the `update` method.
The implementation looks like this:
```java
    @Override
    public void update(Graphics g, JComponent c) {
        SynthContext context = getContext(c);

        SynthLookAndFeel.update(context, g);
        paintBackground(context, g, c);
        paint(context, g);
        context.dispose();
    }
```
And here in the above method, the thing that is responsible
for rendering the button texure (the slight border + soft bright gradient)
is `paintBackground(context, g, c)`.
The stuff that this method renders is the stuff that
is being cut off in the images you attached.
(Thank you by the way for the detailed issue!!)

Here the implementation of the internal `paintBackground`
method:
```java
    void paintBackground(SynthContext context, Graphics g, JComponent c) {
        if (((AbstractButton) c).isContentAreaFilled()) {
            context.getPainter().paintButtonBackground(context, g, 0, 0,
                                                       c.getWidth(),
                                                       c.getHeight());
        }
    }
```
And here we can already see the core problem:
**The nimbus button look and feel ignores the current border
of the button entirely and always fills out the entire component!**

More specifically, the arguments `0, 0, c.getWidth(), c.getHeight()`
alwas reach over the entire component area (which includes the margin).

I looked get other look and feel implementations, and as you would
expect, they access the current `Border` of the component
and subtract the insets from the entire button to only cover the actual "body area", or however you want to call it...

SwingTree does the clipping here on purpose to ensure cirrectness.
The SwingTree `Border` implementation may contain all kinds of things like a round transparent border, or a box shadow.
Not clipping the background may lead to the styles not looking as intended...

So based on that I conclude that this is a Nimbus bug.

But looking through the code I remember having fought with 
this mutiple times already. For various components, not just
buttons, but also combo boxes, nimbus abuses the border 
purely to control the component content insets independently
from the component body instead of introducing their own custom
config for that. But using the `Border` interface like that completely
neglects the idea that clients may want to write their own unique border implementation which neatly wraps around the nimbus component... 

The Nimbus implementation is once again proving to
be absolutely ridiculous on yet another front.

**Comment by Gleethos** [comment]
I doubt that this will ever get fixed, so if you want
to build a feature on this nonsense I actually don't
see a problem with it.
It may become problematic if we ever migrate to a custom
Nimbus fork where we then would probably want to fix these
kind of quirks... But in that case we could certainly add approproate
exceptions for the feature so that it is still correct.
