### ISSUE TITLE
ScrollPane is very inefficient since the introduction of scroll config

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/swing-tree#174]
Since we introduced the new scroll config, I have noticed a very noticeable performance effect when using ScrollPanes.

**Comment by Gleethos** [comment]
Thanks for finding and investigating this.
I believe I know the problem is that the thin wrapper component is just 
completely nonsensical about how it delegates and mimics the content component.
And an override of the `setSize` is completely missing as you pointed out.
I pushed a commit which I believe should fix the issue.

Let me know if this works smoothly now.

For testing you can also use the current commit hash in the Framework to see if it works
and the performance regressions are fixed.
In that case let me know and I will merge this.

**Comment by Mazi-S** [comment]
I tested it and it works in general.

I noticed that when you try to access the viewport pref size, an exception is thrown and when you compare the height of the viewport and the view to determine if the height should be fitted, it flickers. But maybe it is just a misuse of the scroll config.

```Java
// flickers
.fitHeight(config.viewport().getHeight() > config.view().getHeight())
// InvocationTargetException
.fitHeight(config.viewport().getPreferredSize() != null)
```
I updated the test.

**Comment by Gleethos** [comment]
Ok, I will merge this then.
