### ISSUE TITLE
Dynamic TabbedPane

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/swing-tree#188]
It would be very helpful if we could create dynamic tabbedPanes like panels. So that changes to the list are reflected.

```Java
Vars<TabViewModel> tabViewModels = // ...
Vars<ViewModel> viewModels =       // ...

of(this).withLayout("fill, wrap, ins 0")
.add(
    GROW,
    tabbedPane().add(tabViewModels, MyView::toTab)
)
.add(
    GROW,
    panel().add(viewModels, MyView::toPanel)
);
```

```Java
private static Tab toTab(TabViewModel vm) {
    // ...
}

private static UIForPanel<JPanel> toPanel(ViewModel vm) {
    // ...
}
```

Would that be possible?

**Comment by Gleethos** [comment]
I like the idea and this should absolutely be possible.
The API you suggest in the code snippet fits really nicely into 
how this works for other kinds of components.

I think all this needs is an override of the `add` method for the `UIForScrollPane`
and do all of the complex binding stuff there...

**Comment by Gleethos** [comment]
One problem here will however be generic type erasure.
The lambda of the `add(viewModels, MyView::toPanel)` method has a return type which
has to be a `JComponent`.
The suggested `.add(tabViewModels, MyView::toTab)` on the other hand is identical,
except for the return type being a `Tab`, which is a value object, and not a component.

I am not entirely sure, but the compiler might be too stupid to route the two requests
to the correct method overrides because the only difference is the return type.

So that might be a problem.
