### ISSUE TITLE
TransitionalStyle not applied correctly

### ISSUE THREAD

**Issue by Mazi-S** [globaltcad/swing-tree#202]
If a component has a TransitionalStyle and is not displayed when the style changes, the style is incorrect when the component is displayed again.

It seems that when the component is displayed, the lambda is executed correctly once, but the style is not applied. My wild guess is that a `revalidate()` is missing in `swingtree.style.StyleInstaller#_applyDimensionalityStyleTo`, but I'm not familiar with the code.

It is a bit hard to explain, but I will push example that makes it clear.

**Comment by Gleethos** [comment]
> If a component has a TransitionalStyle and is not displayed

Ok, so let me give you some overarching background information to give you a picture:

So I have the suspicion that this is probably based on the fundamental problem
that Swing does not really give SwinTree a clean place and time where to 
hook into and update itself irrespective of the component state.

There are 4 places where we currently hook into the update cycle of 
a component to trigger all of the `Styler` lambda stuff and ultimately the `StylerInstaller`.

- A custom implementation of the `Border` interface
- A custom implementation of the `ComponentUI` interface.
- The `paintComponent(Graphics)` method (native SwingTree components only)
- The `paintChildren(Graphics)` method (native SwingTree components only)

The first one is the `StyleAndAnimationBorder`, it renders the border layer and
also delegates to any former border of the component.
For some components SwingTree has custom `ComponentUI` implementations
(see `DynamicLaF` in the `StyleInstaller`).

And the last two places are found in implementations of the `StylableComponent` interface
usually the ones declared in the `UI` class.
So for example:
```java
    /** {inheritDoc} */
    public static class Slider extends JSlider implements StylableComponent {
        @Override public void paintComponent(Graphics g){ paintBackground(g, super::paintComponent); }
        @Override public void paintChildren(Graphics g) { paintForeground(g, super::paintChildren); }
        @Override public void setUISilently( ComponentUI ui ) { this.ui = ui; }
    }
```

SwingTree works well with any of these hooks. A single one is enough to
trigger an update for the whole styling stuff to take affect...

The problem with all of these hooks however is that they are at the mercy of the
`public void paint(Graphics g)` method of the `JComponent`.
This is what orchestrates calls to the formerly mentioned places...

But this method may not decide to continue its execution in all cases
```java
    public void paint(Graphics g) {
        boolean shouldClearPaintFlags = false;

        if ((getWidth() <= 0) || (getHeight() <= 0)) {
            return;
        }
        [...]
        [...]
    }
```

This is why you will encounter the following condition in the `AnimationRunner`:
```
if ( component.getParent() == null || (component.getWidth() <= 0) || (component.getHeight() <= 0) ) {
    ComponentExtension.from((JComponent) component).gatherApplyAndInstallStyle(false);
    component.revalidate();
    component.repaint();
}
```

So the first problem you outline might be because somewhere in the
Swing code it checks if `JComponent::isVisible` is true and then just returns
without ever triggering a paint cycle (which makes total sense! But it is unfortunate for 
the SwingTree logic).

So from having done debugging before, my assumption is that maybe the above condition
should also check for the visibility of the component. But this is just a guess.

---

> It seems that when the component is displayed, the lambda is executed correctly once, but the style is not applied. My wild guess is that a `revalidate()` is missing in `swingtree.style.StyleInstaller#_applyDimensionalityStyleTo`, but I'm not familiar with the code.

No this is unexpected and I would assume the layout manager to react to the size changes
automatically. At least, that is what the assumption is in the `StylerInstaller` code.
So you might be right that there is indeed a `revalidate()` missing there.

But we should be careful with these statements in there, because there is a danger of 
triggering repeated repaint/revalidate cycles...

**Comment by p10n** [comment]
Maybe invalidate() is enough?

**Comment by Gleethos** [comment]
What exactly is the issue you are facing here in terms of a scenario.
How can I reproduce this?

**Comment by Mazi-S** [comment]
If you have two panels with a transitional style based on a the same property (a foldable panel) placed in different tabs.

```Java
.withTransitionalStyle(isOpen, LifeTime.of(0.5, TimeUnit.SECONDS), (status, style) -> {
    double h = style.component().getPreferredSize().height * status.fadeIn();
    style.component().setBackground( h == 0 ? Color.orange : Color.lightGray);
    System.out.printf("TransitionalStyle[%s]: h=%f\n", content, h);
    return style.minHeight(h).maxHeight(h);
})
```

The invisible foldable panel one is not displayed correctly after the property changes.

Initial state. Both expanded.
![Screenshot from 2024-11-12 09-42-41](https://github.com/user-attachments/assets/3e9272cc-8ded-4d61-a42f-cbd0cb1dd55c) ![Screenshot from 2024-11-12 09-42-48](https://github.com/user-attachments/assets/836f4d5c-26b2-4d61-832c-2ce6e451d88d)

After clicking the Show button on the first tab.
![Screenshot from 2024-11-12 09-43-41](https://github.com/user-attachments/assets/f4587959-2f7b-4e6b-9033-d3d4c0299e9c)![image](https://github.com/user-attachments/assets/0d49ea45-8945-4cda-98f8-e59df7bee8fd)

Another invalid state. The BG color seems to be displayed correctly. Only the size seems to be affected.
![image](https://github.com/user-attachments/assets/2d3b678e-8207-4120-8091-d1e67ff93bd1)

Framework: We want to synchronize the run panels between tabs.
